PROG=		ietd
SRCS=		ietd.c
SRCS+=		iscsid.c
SRCS+=		conn.c
SRCS+=		session.c
SRCS+=		target.c
SRCS+=		message.c
SRCS+=		ctldev.c
SRCS+=		log.c
SRCS+=		chap.c
SRCS+=		event.c
SRCS+=		param.c
SRCS+=		plain.c
SRCS+=		isns.c
SRCS+=		md5.c
SRCS+=		sha1.c

MAN=		ietadm.8

.include <bsd.prog.mk>
